anguage: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
env:
  global:
    - TERM=dumb
  matrix:
    - GRAILS_VERSION=2.4.4
    - GRAILS_VERSION=2.4.5
matrix:
  fast_finish: false
script: chmod ogu+x travis-build.sh ; ./travis-build.sh